name: Prepare, Close and Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0) - Leave empty to detect pending version'
        required: false
      auto_publish:
        description: 'Automatically publish GitHub release after version closing'
        type: boolean
        default: false

# Cancel any running workflow when a new one is triggered
concurrency:
  group: release-pipeline
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  detect-pending-release:
    runs-on: ubuntu-latest
    outputs:
      pending_release: ${{ steps.check-pending.outputs.pending_release }}
      pending_version: ${{ steps.check-pending.outputs.pending_version }}
    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Check for pending release
        id: check-pending
        run: |
          # Get current version and check if tag exists
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          git fetch --tags -q
          git tag -l | grep -q "^v${CURRENT_VERSION}$" && 
          echo "pending_release=false" >> $GITHUB_OUTPUT || 
          { echo "pending_release=true" >> $GITHUB_OUTPUT; 
            echo "pending_version=v${CURRENT_VERSION}" >> $GITHUB_OUTPUT; }

      - name: Explain auto_publish setting
        run: |

          echo "::notice::pending_release=${{ steps.check-pending.outputs.pending_release }}"  
          echo "::notice::pending_version=${{ steps.check-pending.outputs.pending_version }}" 
          if ["${{ github.event.inputs.auto_publish }}" == "true" ]; then
            echo "::notice::AUTO PUBLISH ENABLED: Will create and publish GitHub release"
          else
            echo "::notice::AUTO PUBLISH DISABLED: Will NOT create GitHub release"
          fi

  validate-and-close-version:
    needs: detect-pending-release
    # Only run if NO pending release detected
    if: needs.detect-pending-release.outputs.pending_release == 'false'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - uses: ./.github/actions/setup-node-and-deps

      - name: Validate version increment
        run: |
          # Validate version format
          INPUT_VERSION="${{ github.event.inputs.version }}"
          [[ $INPUT_VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]] || 
          { echo "::error::Invalid version format: $INPUT_VERSION"; exit 1; }

          VERSION=${INPUT_VERSION#v}

          echo "INPUT_VERSION=$INPUT_VERSION" >> $GITHUB_ENV
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          # Compare versions using node semver
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          IS_HIGHER=$(node -e "\
            const semver = require('semver');\
            console.log(semver.gt('$VERSION', '$CURRENT_VERSION') ? 'true' : 'false');\
          ")

          echo "Compare versions -> VERSION: ${VERSION} - CURRENT_VERSION: ${CURRENT_VERSION} - IS_HIGHER: ${IS_HIGHER}"

          [[ "$IS_HIGHER" == "true" ]] || 
          { echo "::error::New version must be higher than current version"; exit 1; }

      - name: Validate Git Flow compliance
        run: |
          # Verify we're on develop branch
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          [[ "$CURRENT_BRANCH" == "develop" ]] || 
          { echo "::error::This workflow must run from develop branch"; exit 1; }

      - uses: ./.github/actions/run-quality-checks

      - name: Check for conflicts with master
        run: |
          # Check for potential merge conflicts
          git fetch origin master -q
          git merge-tree $(git merge-base develop origin/master) develop origin/master > merge_check.txt

          if [ -s merge_check.txt ]; then
            echo "::warning::Potential merge conflicts detected"
            cat merge_check.txt
          fi

      - name: Update versions
        run: |
          # Update version in package.json and manifest.json
          npm version ${{ env.VERSION }} --no-git-tag-version -q
          jq '.version = "${{ env.VERSION }}"' src/manifest.json > temp.json && mv temp.json src/manifest.json

      - uses: ./.github/actions/configure-git

      - name: Commit version changes
        run: |
          # Commit version changes to develop
          git add package.json package-lock.json src/manifest.json
          git commit -m "chore: update version to ${{ env.INPUT_VERSION }}" -q -n
          git push origin develop --no-verify

      - name: Create validation summary
        run: |
          # Generate workflow summary
          echo "## ✅ Version ${{ env.INPUT_VERSION }} validated" >> $GITHUB_STEP_SUMMARY
          echo "- All tests passed" >> $GITHUB_STEP_SUMMARY
          echo "- Version increment validated" >> $GITHUB_STEP_SUMMARY
          echo "- Version updated in develop branch" >> $GITHUB_STEP_SUMMARY

  prepare-release:
    needs: [detect-pending-release, validate-and-close-version]
    # Only run if NO pending release detected
    if: needs.detect-pending-release.outputs.pending_release == 'false'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.validate-and-close-version.outputs.version }}
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - uses: ./.github/actions/configure-git

      - name: Direct merge to master
        run: |
          # Merge develop into master
          git checkout master
          git pull origin master -q
          
          # Try to merge, if conflicts occur, resolve them automatically
          if ! git merge develop --no-ff -m "Merge develop into master for release ${{ needs.validate-and-close-version.outputs.version }}"; then
            echo "Merge conflicts detected, resolving automatically..."
            
            # For version conflicts, always use develop version
            git checkout --theirs package.json package-lock.json src/manifest.json
            
            # Add resolved files and complete merge
            git add .
            git commit -m "Merge develop into master for release ${{ needs.validate-and-close-version.outputs.version }}"
          fi
          
          git push origin master --no-verify

      - name: Create merge summary
        run: |
          # Generate workflow summary
          echo "## ✅ Merged to master" >> $GITHUB_STEP_SUMMARY
          echo "- Develop branch merged to master" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ needs.validate-and-close-version.outputs.version }}" >> $GITHUB_STEP_SUMMARY

  publish-release-new-version:
    needs: [prepare-release]
    if: needs.detect-pending-release.outputs.pending_release == 'false' && github.event.inputs.auto_publish == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Get version from input
        run: |
          INPUT_VERSION="${{ github.event.inputs.version }}" 
          VERSION="${INPUT_VERSION#v}"

          echo "INPUT_VERSION=$INPUT_VERSION" >> $GITHUB_ENV
          echo "VERSION=${INPUT_VERSION#v}" >> $GITHUB_ENV
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - uses: ./.github/actions/setup-node-and-deps

      - uses: ./.github/actions/configure-git

      - uses: ./.github/actions/publish-extension-assets
        with:
          input_version: ${{ env.INPUT_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.VERSION }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.INPUT_VERSION }}
          name: Release ${{ env.INPUT_VERSION }}
          files: ./slack-bitbucket-merge-control-chrome-extension-${{ env.VERSION }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## 🚀 Release ${{ env.INPUT_VERSION }}

            This release was created following Git Flow guidelines from the master branch.

            ### 📦 What's Included
            - Chrome Extension ZIP file ready for Chrome Web Store
            - All features tested and validated
            - Production-ready build

            ### 🔄 Git Flow Compliance
            - **Source Branch**: master
            - **Tag**: ${{ env.INPUT_VERSION }}
            - **Version**: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Publish to Chrome Web Store
        uses: Klemensas/chrome-extension-upload-action@v1
        with:
          app-id: ${{ secrets.CHROME_EXTENSION_ID }}
          refresh-token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
          file-name: ./slack-bitbucket-merge-control-chrome-extension-${{ env.VERSION }}.zip

      - name: Create release summary
        run: |
          # Generate workflow summary
          echo "## 🚀 Release ${{ env.INPUT_VERSION }} Published!" >> $GITHUB_STEP_SUMMARY
          echo "- GitHub release created" >> $GITHUB_STEP_SUMMARY
          echo "- Chrome extension package created" >> $GITHUB_STEP_SUMMARY
          echo "- Published to Chrome Web Store" >> $GITHUB_STEP_SUMMARY
          echo "- Release URL: ${{ steps.create_release.outputs.url }}" >> $GITHUB_STEP_SUMMARY

  publish-release-pending-version:
    needs: [detect-pending-release]
    if: needs.detect-pending-release.outputs.pending_release == 'true' && github.event.inputs.auto_publish == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Get version from pending release
        run: |
          INPUT_VERSION="${{ needs.detect-pending-release.outputs.pending_version }}" 
          VERSION="${INPUT_VERSION#v}"

          echo "INPUT_VERSION=$INPUT_VERSION" >> $GITHUB_ENV
          echo "VERSION=${INPUT_VERSION#v}" >> $GITHUB_ENV
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - uses: ./.github/actions/setup-node-and-deps

      - uses: ./.github/actions/configure-git

      - uses: ./.github/actions/publish-extension-assets
        with:
          input_version: ${{ env.INPUT_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ env.VERSION }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.INPUT_VERSION }}
          name: Release ${{ env.INPUT_VERSION }}
          files: ./slack-bitbucket-merge-control-chrome-extension-${{ env.VERSION }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          body: |
            ## 🚀 Release ${{ env.INPUT_VERSION }}

            This release was created following Git Flow guidelines from the master branch.

            ### 📦 What's Included
            - Chrome Extension ZIP file ready for Chrome Web Store
            - All features tested and validated
            - Production-ready build

            ### 🔄 Git Flow Compliance
            - **Source Branch**: master
            - **Tag**: ${{ env.INPUT_VERSION }}
            - **Version**: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Publish to Chrome Web Store
        uses: Klemensas/chrome-extension-upload-action@v1
        with:
          app-id: ${{ secrets.CHROME_EXTENSION_ID }}
          refresh-token: ${{ secrets.CHROME_WEB_STORE_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_WEB_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_WEB_STORE_CLIENT_SECRET }}
          file-name: ./slack-bitbucket-merge-control-chrome-extension-${{ env.VERSION }}.zip

      - name: Create release summary
        run: |
          # Generate workflow summary
          echo "## 🚀 Release ${{ env.INPUT_VERSION }} Published!" >> $GITHUB_STEP_SUMMARY
          echo "- GitHub release created" >> $GITHUB_STEP_SUMMARY
          echo "- Chrome extension package created" >> $GITHUB_STEP_SUMMARY
          echo "- Published to Chrome Web Store" >> $GITHUB_STEP_SUMMARY
          echo "- Release URL: ${{ steps.create_release.outputs.url }}" >> $GITHUB_STEP_SUMMARY