name: Sync Bug Documentation to GitHub Issues

on:
  push:
    branches:
      - master
    paths:
      - 'documentation/bugs/[0-9]*.md'

jobs:
  sync-bugs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # To get the previous commit for comparison
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: documentation/bugs/[0-9]*.md
      
      - name: Process new bug files
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Define the full path to the script
            const scriptPath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'scripts', 'sync-bug-to-issue.js');
            console.log(`Loading script from: ${scriptPath}`);
            
            // Import the external script using dynamic import with absolute path
            const syncBugToIssueModule = await import(`file://${scriptPath}`);
            const syncBugToIssue = syncBugToIssueModule.default;
            
            // Process each changed bug file
            const changedFiles = '${{ steps.changed-files.outputs.all_changed_files }}'.split(' ');
            const results = [];
            
            for (const file of changedFiles) {
              // Only process new bug files
              if (!file.match(/documentation\/bugs\/\d{3}-.+\.md$/)) continue;
              
              // Execute the script with all required parameters
              const result = await syncBugToIssue({ 
                github, 
                context, 
                core, 
                exec, 
                fs, 
                path,
                file 
              });
              
              if (result) {
                results.push(result);
              }
            }
            
            return results;
