name: Sync GitHub Issues to Bug Documentation

on:
  issues:
    types: [opened, labeled]

jobs:
  sync-to-bug-files:
    runs-on: ubuntu-latest
    # Only run for issues with the 'bug' label
    if: contains(github.event.issue.labels.*.name, 'bug')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Use a personal access token to allow the workflow to commit changes
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Create bug file from issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Import the external script
            const syncIssueToDoc = require('./.github/scripts/sync-issue-to-bug.js');
            
            // Execute the script with all required parameters
            return await syncIssueToDoc({ 
              github, 
              context, 
              core, 
              exec, 
              fs, 
              path 
            });
