name: Update Bug Index Table

on:
  push:
    branches:
      - master
    paths:
      - 'documentation/bugs/[0-9]*.md'
  workflow_dispatch: # Permite ejecutar manualmente el workflow

# Define los permisos necesarios para el GITHUB_TOKEN
permissions:
  contents: write # Para hacer push de cambios

jobs:
  update-bug-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Use a personal access token to allow the workflow to commit changes
          token: ${{ secrets.PAT_TOKEN || github.token }}

      - name: Update bug index
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Define the full path to the script
            const scriptPath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'scripts', 'update-bug-index.js');
            console.log(`Loading script from: ${scriptPath}`);

            // Import the external script using dynamic import with absolute path
            const updateBugIndexModule = await import(`file://${scriptPath}`);
            const updateBugIndex = updateBugIndexModule.default;

            // Execute the script with all required parameters
            return await updateBugIndex({ 
              fs, 
              path 
            });

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code documentation/bugs/README.md || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          # Set up git user
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          # Commit and push changes
          git add documentation/bugs/README.md
          git commit -m "[AUTOMATED] Update bug index table [skip-issue-creation]"
          git push
